language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -e .
  # install develop branch of ibllib
  - pip install git+https://github.com/int-brain-lab/ibllib.git@develop

 # command to run tests
before_script:
  - echo "exec('from oneibl.one import ONE; ONE(silent=True)')" | python
  - sed -i 's|null|"'$IBLFLATIRONPASS'"|g' /home/travis/.one_params
  # command to run tests

script:
  - bash ./run_tests
  - flake8 .

# only build master and develop (PRs are built for all branches)
branches:
  only:
  - master
  - develop
